-- Скрипт для автоматической загрузки данных при запуске приложения
-- (альтернатива Flyway migration, если не используется Flyway)

-- ВНИМАНИЕ: Этот файл выполняется только если в application.yml установлено:
-- spring.jpa.hibernate.ddl-auto=create или create-drop
-- И spring.sql.init.mode=always

-- Если используете Flyway, этот файл можно удалить

CREATE TABLE audit_logs
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    deleted     BOOLEAN                                 NOT NULL,
    user_id     BIGINT,
    username    VARCHAR(50),
    action      VARCHAR(50)                             NOT NULL,
    entity_type VARCHAR(100),
    entity_id   BIGINT,
    description TEXT,
    old_value   TEXT,
    new_value   TEXT,
    ip_address  VARCHAR(45),
    user_agent  VARCHAR(500),
    CONSTRAINT pk_audit_logs PRIMARY KEY (id)
);

CREATE TABLE departments
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    deleted     BOOLEAN                                 NOT NULL,
    code        VARCHAR(20)                             NOT NULL,
    name        VARCHAR(200)                            NOT NULL,
    description TEXT,
    parent_id   BIGINT,
    active      BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_departments PRIMARY KEY (id)
);

CREATE TABLE material_categories
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    deleted     BOOLEAN                                 NOT NULL,
    code        VARCHAR(20)                             NOT NULL,
    name        VARCHAR(200)                            NOT NULL,
    description TEXT,
    parent_id   BIGINT,
    active      BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_material_categories PRIMARY KEY (id)
);

CREATE TABLE material_movements
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    deleted         BOOLEAN                                 NOT NULL,
    material_id     BIGINT                                  NOT NULL,
    movement_type   VARCHAR(20)                             NOT NULL,
    quantity        DECIMAL(15, 3)                          NOT NULL,
    quantity_before DECIMAL(15, 3),
    quantity_after  DECIMAL(15, 3),
    request_id      BIGINT,
    user_id         BIGINT,
    department_id   BIGINT,
    document_number VARCHAR(100),
    notes           TEXT,
    unit_price      DECIMAL(15, 2),
    total_price     DECIMAL(15, 2),
    CONSTRAINT pk_material_movements PRIMARY KEY (id)
);

CREATE TABLE materials
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    deleted            BOOLEAN                                 NOT NULL,
    article            VARCHAR(50)                             NOT NULL,
    name               VARCHAR(300)                            NOT NULL,
    description        TEXT,
    category_id        BIGINT                                  NOT NULL,
    unit_of_measure    VARCHAR(20)                             NOT NULL,
    current_quantity   DECIMAL(15, 3)                          NOT NULL,
    min_quantity       DECIMAL(15, 3),
    max_quantity       DECIMAL(15, 3),
    critical_quantity  DECIMAL(15, 3),
    storage_location   VARCHAR(200),
    warehouse_type     VARCHAR(50),
    storage_conditions TEXT,
    unit_price         DECIMAL(15, 2),
    manufacturer       VARCHAR(200),
    supplier           VARCHAR(200),
    barcode            VARCHAR(100),
    image_url          VARCHAR(500),
    active             BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_materials PRIMARY KEY (id)
);

CREATE TABLE notifications
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    deleted             BOOLEAN                                 NOT NULL,
    user_id             BIGINT                                  NOT NULL,
    title               VARCHAR(200)                            NOT NULL,
    message             TEXT,
    type                VARCHAR(50),
    is_read             BOOLEAN                                 NOT NULL,
    related_entity_type VARCHAR(50),
    related_entity_id   BIGINT,
    CONSTRAINT pk_notifications PRIMARY KEY (id)
);

CREATE TABLE request_items
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    deleted            BOOLEAN                                 NOT NULL,
    request_id         BIGINT                                  NOT NULL,
    material_id        BIGINT                                  NOT NULL,
    requested_quantity DECIMAL(15, 3)                          NOT NULL,
    approved_quantity  DECIMAL(15, 3),
    issued_quantity    DECIMAL(15, 3),
    notes              TEXT,
    CONSTRAINT pk_request_items PRIMARY KEY (id)
);

CREATE TABLE requests
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    deleted          BOOLEAN                                 NOT NULL,
    request_number   VARCHAR(50)                             NOT NULL,
    status           VARCHAR(30)                             NOT NULL,
    requester_id     BIGINT                                  NOT NULL,
    department_id    BIGINT                                  NOT NULL,
    purpose          VARCHAR(500)                            NOT NULL,
    notes            TEXT,
    approved_by_id   BIGINT,
    approved_at      TIMESTAMP WITHOUT TIME ZONE,
    issued_by_id     BIGINT,
    issued_at        TIMESTAMP WITHOUT TIME ZONE,
    rejection_reason TEXT,
    priority         INTEGER,
    expected_date    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_requests PRIMARY KEY (id)
);

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    deleted       BOOLEAN                                 NOT NULL,
    username      VARCHAR(50)                             NOT NULL,
    password      VARCHAR(255)                            NOT NULL,
    email         VARCHAR(100)                            NOT NULL,
    last_name     VARCHAR(100)                            NOT NULL,
    first_name    VARCHAR(100)                            NOT NULL,
    middle_name   VARCHAR(100),
    role          VARCHAR(20)                             NOT NULL,
    department_id BIGINT,
    phone         VARCHAR(20),
    position      VARCHAR(100),
    work_group    VARCHAR(20),
    active        BOOLEAN                                 NOT NULL,
    last_login    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE departments
    ADD CONSTRAINT uc_departments_code UNIQUE (code);

ALTER TABLE material_categories
    ADD CONSTRAINT uc_material_categories_code UNIQUE (code);

ALTER TABLE materials
    ADD CONSTRAINT uc_materials_article UNIQUE (article);

ALTER TABLE requests
    ADD CONSTRAINT uc_requests_request_number UNIQUE (request_number);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

CREATE INDEX idx_audit_action ON audit_logs (action);

CREATE INDEX idx_audit_date ON audit_logs (created_at);

CREATE INDEX idx_audit_entity ON audit_logs (entity_type, entity_id);

CREATE INDEX idx_category_code ON material_categories (code);

CREATE INDEX idx_department_code ON departments (code);

CREATE INDEX idx_material_article ON materials (article);

CREATE INDEX idx_material_name ON materials (name);

CREATE INDEX idx_movement_date ON material_movements (created_at);

CREATE INDEX idx_movement_type ON material_movements (movement_type);

CREATE INDEX idx_notification_date ON notifications (created_at);

CREATE INDEX idx_notification_read ON notifications (is_read);

CREATE INDEX idx_request_number ON requests (request_number);

CREATE INDEX idx_request_status ON requests (status);

CREATE INDEX idx_user_email ON users (email);

CREATE INDEX idx_user_username ON users (username);

ALTER TABLE audit_logs
    ADD CONSTRAINT FK_AUDIT_LOGS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

CREATE INDEX idx_audit_user ON audit_logs (user_id);

ALTER TABLE departments
    ADD CONSTRAINT FK_DEPARTMENTS_ON_PARENT FOREIGN KEY (parent_id) REFERENCES departments (id);

ALTER TABLE materials
    ADD CONSTRAINT FK_MATERIALS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES material_categories (id);

ALTER TABLE material_categories
    ADD CONSTRAINT FK_MATERIAL_CATEGORIES_ON_PARENT FOREIGN KEY (parent_id) REFERENCES material_categories (id);

ALTER TABLE material_movements
    ADD CONSTRAINT FK_MATERIAL_MOVEMENTS_ON_DEPARTMENT FOREIGN KEY (department_id) REFERENCES departments (id);

ALTER TABLE material_movements
    ADD CONSTRAINT FK_MATERIAL_MOVEMENTS_ON_MATERIAL FOREIGN KEY (material_id) REFERENCES materials (id);

CREATE INDEX idx_movement_material ON material_movements (material_id);

ALTER TABLE material_movements
    ADD CONSTRAINT FK_MATERIAL_MOVEMENTS_ON_REQUEST FOREIGN KEY (request_id) REFERENCES requests (id);

CREATE INDEX idx_movement_request ON material_movements (request_id);

ALTER TABLE material_movements
    ADD CONSTRAINT FK_MATERIAL_MOVEMENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE notifications
    ADD CONSTRAINT FK_NOTIFICATIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

CREATE INDEX idx_notification_user ON notifications (user_id);

ALTER TABLE requests
    ADD CONSTRAINT FK_REQUESTS_ON_APPROVED_BY FOREIGN KEY (approved_by_id) REFERENCES users (id);

ALTER TABLE requests
    ADD CONSTRAINT FK_REQUESTS_ON_DEPARTMENT FOREIGN KEY (department_id) REFERENCES departments (id);

ALTER TABLE requests
    ADD CONSTRAINT FK_REQUESTS_ON_ISSUED_BY FOREIGN KEY (issued_by_id) REFERENCES users (id);

ALTER TABLE requests
    ADD CONSTRAINT FK_REQUESTS_ON_REQUESTER FOREIGN KEY (requester_id) REFERENCES users (id);

CREATE INDEX idx_request_requester ON requests (requester_id);

ALTER TABLE request_items
    ADD CONSTRAINT FK_REQUEST_ITEMS_ON_MATERIAL FOREIGN KEY (material_id) REFERENCES materials (id);

CREATE INDEX idx_request_item_material ON request_items (material_id);

ALTER TABLE request_items
    ADD CONSTRAINT FK_REQUEST_ITEMS_ON_REQUEST FOREIGN KEY (request_id) REFERENCES requests (id);

CREATE INDEX idx_request_item_request ON request_items (request_id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_DEPARTMENT FOREIGN KEY (department_id) REFERENCES departments (id);